### ISSUE TITLE
[BUG][opensearch] log4j2 configuration error

### ISSUE THREAD

**Issue by skeggr** [opensearch-project/helm-charts#208]
**Describe the bug**
Possibly it's not a bug, but if you enable trace logging for openid issues debugging as described here: https://opensearch.org/docs/latest/troubleshoot/openid-connect/#set-log-level-to-debug - opensearch cannot start

**To Reproduce**
1. Add helm repo
2. Add logger.plugins.security* lines to log4j2 configuration section of values file:
```
  config:
    log4j2.properties: |
         status = error
         appender.console.type = Console
         appender.console.name = console
         appender.console.layout.type = PatternLayout
         appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
         rootLogger.level = debug
         rootLogger.appenderRef.console.ref = console
         logger.plugins.security.name = com.amazon.dlic.auth.http.jwt
         logger.plugins.security.level = trace
```
3. Try to install chart
Install fails, pod logs:
```
Enabling OpenSearch Security Plugin
Exception in thread "main" org.apache.logging.log4j.core.config.ConfigurationException: No name attribute provided for Logger plugins
        at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createLogger(PropertiesConfigurationBuilder.java:256)
        at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:178)
        at org.opensearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:228)
        at org.opensearch.common.logging.LogConfigurator$2.getConfiguration(LogConfigurator.java:197)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:302)
        at org.opensearch.common.logging.LogConfigurator$3.visitFile(LogConfigurator.java:236)
        at org.opensearch.common.logging.LogConfigurator$3.visitFile(LogConfigurator.java:232)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
        at org.opensearch.common.logging.LogConfigurator.configure(LogConfigurator.java:232)
        at org.opensearch.common.logging.LogConfigurator.configure(LogConfigurator.java:142)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:373)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
For complete error details, refer to the log at /usr/share/opensearch/logs/opensearch-cluster.log
Killing performance analyzer process 11
OpenSearch exited with code 1
```

**Expected behavior**
Opensearch run succesfully with enabled verbose logging

**Chart Name**
opensearch-1.5.7

**Host/Environment (please complete the following information):**
 - Helm Version: 3.7
 - Kubernetes Version: 1.21.7

**Additional context**

Chart installs successfully without  two logger.plugins.security* lines, so other log4j2 parameters works well.

**Comment by peterzhuamazon** [comment]
Hi @skeggr is this still an issue now?
Thanks.

**Comment by skeggr** [comment]
Hi, it's not an issue for me anymore, because I've already found why OpenID auth was not working. But for someone this trace logs could be useful.

**Comment by peterzhuamazon** [comment]
Close the issue as it has been resolved by community member.
Feel free to open if needed.
You can always find this issue in closed tab.

Thanks.

**Comment by orest-gulman** [comment]
> Close the issue as it has been resolved by community member.
How it was resolved?
