### ISSUE TITLE
[BUG] OpenSearchException: Transport client authentication no longer supported

### ISSUE THREAD

**Issue by albgus** [opensearch-project/helm-charts#345]
**What is the bug?**
When starting an OpenSearch cluster from the Helm chart and attempting the nodes start, but are throwing an exception because they're apparently not allowed to communicate.

**How can one reproduce the bug?**
1. Follow the OpenSeach Helm installation guide: https://opensearch.org/docs/latest/opensearch/install/helm/
2. Go through the undocumented step of generating certificates
3. Deploy the Helm chart

**What is the expected behavior?**
The cluster should start and the nodes should be able to communicate with each other.

**What is your host/environment?**
 - OS: AWS EKS 1.23
 - OpenSearch version: 2.3.0
 - Plugins: default

**Do you have any screenshots?**

**Do you have any additional context?**
values (including config)
```
# Allows you to add any config files in {{ .Values.opensearchHome }}/config
opensearchHome: /usr/share/opensearch
# such as opensearch.yml and log4j2.properties
config:
  # Values must be YAML literal style scalar / YAML multiline string.
  # <filename>: |
  #   <formatted-value(s)>
  # log4j2.properties: |
  #   status = error
  #
  #   appender.console.type = Console
  #   appender.console.name = console
  #   appender.console.layout.type = PatternLayout
  #   appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
  #
  #   rootLogger.level = info
  #   rootLogger.appenderRef.console.ref = console
  opensearch.yml: |
    cluster.name: test-cluster
    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0
    # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
    # Implicitly done if ".singleNode" is set to "true".
    # discovery.type: single-node
    # Start OpenSearch Security Demo Configuration
    # WARNING: revise all the lines below before you go into production
    plugins:
      security:
        ssl:
          transport:
            pemcert_filepath: /usr/share/opensearch/config/certs/node.crt
            pemkey_filepath: /usr/share/opensearch/config/certs/node.key
            pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
            enforce_hostname_verification: false
          http:
            enabled: true
            pemcert_filepath: /usr/share/opensearch/config/certs/node.crt
            pemkey_filepath: /usr/share/opensearch/config/certs/node.key
            pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
        allow_unsafe_democertificates: false
        allow_default_init_securityindex: true
        authcz:
          admin_dn: # Generated by generate-certs.sh
            - CN=admin,OU=test-cluster
        audit.type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
          roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
          enabled: true
          indices:
            [
              ".opendistro-alerting-config",
              ".opendistro-alerting-alert*",
              ".opendistro-anomaly-results*",
              ".opendistro-anomaly-detector*",
              ".opendistro-anomaly-checkpoints",
              ".opendistro-anomaly-detection-state",
              ".opendistro-reports-*",
              ".opendistro-notifications-*",
              ".opendistro-notebooks",
              ".opendistro-asynchronous-search-response*",
            ]
    ######## End OpenSearch Security Demo Configuration ########
  # log4j2.properties:
```

Logs:
```
[2022-11-01T15:07:23,402][ERROR][o.o.s.t.SecurityRequestHandler] [test-cluster-master-1] OpenSearchException[Transport client authentication no longer supported.]
[2022-11-01T15:07:23,581][ERROR][o.o.s.t.SecurityRequestHandler] [test-cluster-master-1] OpenSearchException[Transport client authentication no longer supported.]
[2022-11-01T15:07:23,848][WARN ][o.o.d.HandshakingTransportAddressConnector] [test-cluster-master-1] handshake failed for [connectToRemoteMasterNode[10.60.133.227:9300]]
org.opensearch.transport.RemoteTransportException: [test-cluster-master-2][10.60.133.227:9300][internal:transport/handshake]
Caused by: org.opensearch.OpenSearchException: Transport client authentication no longer supported.
        at org.opensearch.security.ssl.util.ExceptionUtils.createTransportClientNoLongerSupportedException(ExceptionUtils.java:63) ~[?:?]
        at org.opensearch.security.transport.SecurityRequestHandler.messageReceivedDecorate(SecurityRequestHandler.java:265) ~[?:?]
        at org.opensearch.security.ssl.transport.SecuritySSLRequestHandler.messageReceived(SecuritySSLRequestHandler.java:152) ~[?:?]
        at org.opensearch.security.OpenSearchSecurityPlugin$7$1.messageReceived(OpenSearchSecurityPlugin.java:658) ~[?:?]
        at org.opensearch.indexmanagement.rollup.interceptor.RollupInterceptor$interceptHandler$1.messageReceived(RollupInterceptor.kt:100) ~[?:?]
        at org.opensearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) ~[?:?]
        at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:106) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundHandler.handleRequest(InboundHandler.java:249) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundHandler.messageReceived(InboundHandler.java:132) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundHandler.inboundMessage(InboundHandler.java:114) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.TcpTransport.inboundMessage(TcpTransport.java:769) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:175) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:150) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:115) ~[opensearch-2.3.0.jar:2.3.0]
        at org.opensearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:94) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by albgus** [comment]
After another day of trial and error it seems that replacing the certificates with ones genrated by the OpenSearch operator (which has a bunch of other issues) makes it work... I have no idea why but I'm fairly confident that it's not really a bug of the Helm chart.

I think this is more of an issue that there is no documentation on how to set up an OpenSearch cluster in anything other than an insecure testing setup. It appears that there is some specialized requirement of the certificates to make them work without throwing cryptic error messages.

**Comment by albgus** [comment]
I feel a bit stupid now but I've somehow managed to gloss over this page in the docs: https://opensearch.org/docs/latest/security-plugin/configuration/generate-certificates/

Furthermore it seems that the trick here is to add "Registered ID: 1.2.3.4.5.5", to allow the cluster to work without specifying nodes_dn: (which was the discrepancy between the example config) 

```
openssl req -new -nodes -out node.csr -newkey rsa:4096 -keyout node.tmp.key -subj "/CN=node/OU=$cluster_name/"
openssl pkcs8 -inform PEM -outform PEM -in node.tmp.key -topk8 -nocrypt -v1 PBE-SHA1-3DES -out node.key
openssl x509 -req -in node.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out $1.crt -days 3650 -sha256 -passin -extfile extfile.tmp
```
with extfile: `subjectAltName=RID:1.2.3.4.5.5,DNS:$cluster_name`

**Comment by peternied** [comment]
@albgus Thanks for sharing your journey - you aren't alone on missing a step in the process, just recently I was attempting to reproduce build failures for windows platform ... on a linux machine.

If you have any thoughts on how the documentation could be improved or augmented feel free to drop in to `documentation-website` [1] with any suggestions through issues or maybe even a pull request.

[1] https://github.com/opensearch-project/documentation-website

**Comment by peternied** [comment]
FYI @cwillum - He is the championing the security plugin's documentation.

**Comment by torbenaa** [comment]
Same journey here - just spent a whole day figuring out that I missed the RID entry in the SAN field of my custom certificates. The docs says NOTHING about that - the example script either.

**Comment by cwillum** [comment]
@albgus @torbenaa Feeling the pain after reading your comments. I added a documentation issue to begin addressing this problem. You can have a look, add anything you want/feel is appropriate, and track progress in issue #[2423](https://github.com/opensearch-project/documentation-website/issues/2423).

**Comment by Nmishin** [comment]
I had the same issue, and in my case, it was incorrect certificate DNs in `adminDn` initially. Once I figured it out and fixed it, the pod `securityconfig-update` started providing a lot of useful information, and I realized I had the same issue in `nodesDn`.
