### ISSUE TITLE
[BUG][Opensearch] DISABLE_INSTALL_DEMO_CONFIG dropped in wrong place in helm manifest

### ISSUE THREAD

**Issue by jdblack** [opensearch-project/helm-charts#370]
**Describe the bug**
I'm attempting to deploy opensearch via the opensearch helm chart,  via terraform deployment.  As part of  this process, I'm  trying to provide  SSL certs that were generated by cert-manager and trying to disable the demo certs with DISABLE_INSTALL_DEMO_CONFIG.  However, it appears that the generated helm file within K8s itself is putting DISABLE_INSTALL_DEMO_CONFIG  one level too high, e.g.  adjacent to env, rather than under it.

This misplacement ultimately results in
[2023-01-07T09:06:10,417][ERROR][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Demo certificates found but plugins.security.allow_unsafe_democertificates is set to false.

**To Reproduce**

### The opensearch terraform module that I'm building
```
locals {
  os_domain = "search-${var.domains[0]}"
  cert_path = "/usr/share/opensearch/config/tls"
  clusterName = "search-cinc"
  opensearch_values = [ yamlencode({
    extraEnvs = {
        DISABLE_INSTALL_DEMO_CONFIG = true
      }
    clusterName = local.clusterName
    singleNode = true
    masterService = "${local.clusterName}-master"
    persistence = {
      enabled = false
    }
    service = {
      type = "LoadBalancer"
    }
    secretMounts = [
      {
        name = "certs"
        path = local.cert_path
        secretName = module.opensearch-cert.secret
        defaultMode = "0400"
      }
    ]
    config = {
      "opensearch.yml" =  {
        cluster = {
          name = local.clusterName
        }
        plugins = {
          security = {
            allow_default_init_securityindex = true
            ssl = {
              transport = {
                pemcert_filepath = "tls/tls.crt"
                pemkey_filepath = "tls/tls.key"
                pemtrustedcas_filepath = "tls/ca.crt"
                enforce_hostname_verification = false
              }
              http = {
                pemcert_filepath = "tls/tls.crt"
                pemkey_filepath = "tls/tls.key"
                pemtrustedcas_filepath = "tls/ca.crt"
              }
            }
          }
        }
      }
    }
  })]
}

module "opensearch-cert" {
  source = "../server_cert"
  namespace = var.namespace
  name = "opensearch-cinc"
  cert_domains = [local.os_domain]
  issuer = var.cert_issuer
}

resource "helm_release" "opensearch" {
  namespace  = var.namespace
  name       = "opensearch"
  repository = "https://opensearch-project.github.io/helm-charts/"
  chart      = "opensearch"
  values = local.opensearch_values

  set {
    name = "service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
    value = local.os_domain
    type = "string"
  }
}
```

### The resulting terraform plan. 
As can be seen,  DISABLE_INSTALL_DEMO_CONFIG shows up in extraEnvs
 
```
  # module.cinc.helm_release.opensearch will be created
  + resource "helm_release" "opensearch" {
      + atomic                     = false
      + chart                      = "opensearch"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "opensearch"
      + namespace                  = "cinc"
      + pass_credentials           = false
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://opensearch-project.github.io/helm-charts/"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + values                     = [
          + <<-EOT
                "clusterName": "search-cinc"
                "config":
                  "opensearch.yml":
                    "cluster":
                      "name": "search-cinc"
                    "plugins":
                      "security":
                        "allow_default_init_securityindex": true
                        "ssl":
                          "http":
                            "pemcert_filepath": "tls/tls.crt"
                            "pemkey_filepath": "tls/tls.key"
                            "pemtrustedcas_filepath": "tls/ca.crt"
                          "transport":
                            "enforce_hostname_verification": false
                            "pemcert_filepath": "tls/tls.crt"
                            "pemkey_filepath": "tls/tls.key"
                            "pemtrustedcas_filepath": "tls/ca.crt"
                "extraEnvs":
                  "DISABLE_INSTALL_DEMO_CONFIG": true
                "masterService": "search-cinc-master"
                "persistence":
                  "enabled": false
                "secretMounts":
                - "defaultMode": "0400"
                  "name": "certs"
                  "path": "/usr/share/opensearch/config/tls"
                  "secretName": "opensearch-cinc"
                "service":
                  "type": "LoadBalancer"
                "singleNode": true
            EOT,
        ]
      + verify                     = false
      + version                    = "2.9.1"
      + wait                       = true
      + wait_for_jobs              = false

      + set {
          + name  = "service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
          + type  = "string"
          + value = "search-cinc.vn.linuxguru.net"
        }
    }
```
### The manifest that arrives in K8s as per "helm get manifest"
Note that DISABLE_INSTALL_DEMO_CONFIG  is at the same level as clusterName, rather than subordinate to env.

```
---
# Source: opensearch/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "search-cinc-master-pdb"
  labels:
    helm.sh/chart: opensearch-2.9.1
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: search-cinc-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/instance: opensearch
---
# Source: opensearch/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-cinc-master-config
  labels:
    helm.sh/chart: opensearch-2.9.1
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: search-cinc-master
data:
  opensearch.yml: |
    cluster:
      name: search-cinc
    plugins:
      security:
        allow_default_init_securityindex: true
        ssl:
          http:
            pemcert_filepath: tls/tls.crt
            pemkey_filepath: tls/tls.key
            pemtrustedcas_filepath: tls/ca.crt
          transport:
            enforce_hostname_verification: false
            pemcert_filepath: tls/tls.crt
            pemkey_filepath: tls/tls.key
            pemtrustedcas_filepath: tls/ca.crt
---
# Source: opensearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: search-cinc-master
  labels:
    helm.sh/chart: opensearch-2.9.1
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: search-cinc-master
  annotations:
    external-dns.alpha.kubernetes.io/hostname: search-cinc.vn.linuxguru.net
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
---
# Source: opensearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: search-cinc-master-headless
  labels:
    helm.sh/chart: opensearch-2.9.1
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: search-cinc-master
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None # This is needed for statefulset hostnames like opensearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
---
# Source: opensearch/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: search-cinc-master
  labels:
    helm.sh/chart: opensearch-2.9.1
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: search-cinc-master
  annotations:
    majorVersion: "2"
spec:
  serviceName: search-cinc-master-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/instance: opensearch
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "search-cinc-master"
      labels:
        helm.sh/chart: opensearch-2.9.1
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/version: "2.4.1"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: search-cinc-master
      annotations:
        configchecksum: a214d0046141d02de8cf064552559e49c4fe593d600fd4d5f1b6b0cceacd826
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - opensearch
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - opensearch
      terminationGracePeriodSeconds: 120
      volumes:
      - name: certs
        secret:
          secretName: opensearch-cinc
          defaultMode: 0400
      - name: config
        configMap:
          name: search-cinc-master-config
      enableServiceLinks: true
      containers:
      - name: "opensearch"
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
  
        image: "opensearchproject/opensearch:2.4.1"
        imagePullPolicy: "IfNotPresent"
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 5
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 9200
          timeoutSeconds: 3
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          requests:
            cpu: 1000m
            memory: 100Mi
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "search-cinc-master-headless"
        - name: cluster.name
          value: "search-cinc"
        - name: network.host
          value: "0.0.0.0"
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xmx512M -Xms512M"
        - name: node.roles
          value: "master,ingest,data,remote_cluster_client,"
        - name: discovery.type
          value: "single-node"
        DISABLE_INSTALL_DEMO_CONFIG: true
        volumeMounts:
        - name: certs
          mountPath: /usr/share/opensearch/config/tls
        - name: config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
```

**Expected behavior**
I expect setting DISABLE_INSTALL_DEMO_CONFIG under extraEnvs will cause the stateful set to get DISABLE_INSTALL_DEMO_CONFIG within the environment.

**Chart Name**
opensearch

**Host/Environment (please complete the following information):**
 - Helm Version:  version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
 - Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
 - Terraform version : Terraform v1.3.6

**Additional context**
The container log
```
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-2.4.1
Detected OpenSearch Security Version: 2.4.1.0

tee: /usr/share/opensearch/config/opensearch.yml: Permission denied
Enabling OpenSearch Security Plugin
Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/opensearch/lib/opensearch-2.4.1.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/opensearch/lib/opensearch-2.4.1.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
WARNING: System::setSecurityManager will be removed in a future release
[2023-01-07T09:06:04,979][INFO ][o.o.n.Node               ] [search-cinc-master-0] version[2.4.1], pid[46], build[tar/f2f809ea280ffba217451da894a5899f1cec02ab/2022-12-12T22:17:42.341124910Z], OS[Linux/5.15.0-56-generic/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.5/17.0.5+8]
[2023-01-07T09:06:04,986][INFO ][o.o.n.Node               ] [search-cinc-master-0] JVM home [/usr/share/opensearch/jdk], using bundled JDK [true]
[2023-01-07T09:06:04,987][INFO ][o.o.n.Node               ] [search-cinc-master-0] JVM arguments [-Xshare:auto, -Dopensearch.networkaddress.cache.ttl=60, -Dopensearch.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/opensearch-4115586670611177846, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Djava.security.policy=/usr/share/opensearch/config/opensearch-performance-analyzer/opensearch_security.policy, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, -Dopensearch.cgroups.hierarchy.override=/, -Xmx512M, -Xms512M, -XX:MaxDirectMemorySize=268435456, -Dopensearch.path.home=/usr/share/opensearch, -Dopensearch.path.conf=/usr/share/opensearch/config, -Dopensearch.distribution.type=tar, -Dopensearch.bundled_jdk=true]
[2023-01-07T09:06:08,110][WARN ][stderr                   ] [search-cinc-master-0] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[2023-01-07T09:06:08,111][WARN ][stderr                   ] [search-cinc-master-0] SLF4J: Defaulting to no-operation (NOP) logger implementation
[2023-01-07T09:06:08,111][WARN ][stderr                   ] [search-cinc-master-0] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2023-01-07T09:06:08,147][INFO ][o.o.s.s.t.SSLConfig      ] [search-cinc-master-0] SSL dual mode is disabled
[2023-01-07T09:06:08,148][INFO ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] OpenSearch Config path is /usr/share/opensearch/config
[2023-01-07T09:06:08,954][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] JVM supports TLSv1.3
[2023-01-07T09:06:08,957][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] Config directory is /usr/share/opensearch/config/, from there the key- and truststore files are resolved relatively
[2023-01-07T09:06:10,296][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] TLS Transport Client Provider : JDK
[2023-01-07T09:06:10,296][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] TLS Transport Server Provider : JDK
[2023-01-07T09:06:10,297][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] TLS HTTP Provider             : null
[2023-01-07T09:06:10,297][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2]
[2023-01-07T09:06:10,298][INFO ][o.o.s.s.DefaultSecurityKeyStore] [search-cinc-master-0] Enabled TLS protocols for HTTP layer      : []
[2023-01-07T09:06:10,346][INFO ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Clustername: search-cinc
[2023-01-07T09:06:10,370][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Directory /usr/share/opensearch/config has insecure file permissions (should be 0700)
[2023-01-07T09:06:10,370][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/opensearch.yml has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,371][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/kirk.pem has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,372][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/kirk-key.pem has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,372][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/esnode-key.pem has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,373][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/esnode.pem has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,373][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Directory /usr/share/opensearch/config/tls has insecure file permissions (should be 0700)
[2023-01-07T09:06:10,374][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/tls/tls.key has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,375][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/tls/tls.crt has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,375][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/tls/ca.crt has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,376][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/tls/..data has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,376][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Directory /usr/share/opensearch/config/tls/..2023_01_07_08_37_24.3779218821 has insecure file permissions (should be 0700)
[2023-01-07T09:06:10,377][WARN ][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] File /usr/share/opensearch/config/root-ca.pem has insecure file permissions (should be 0600)
[2023-01-07T09:06:10,417][ERROR][o.o.s.OpenSearchSecurityPlugin] [search-cinc-master-0] Demo certificates found but plugins.security.allow_unsafe_democertificates is set to false.
[2023-01-07T09:06:10,425][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [search-cinc-master-0] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.4.1.jar:2.4.1]
	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.4.1.jar:2.4.1]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:790) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:426) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:353) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.4.1.jar:2.4.1]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:426) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:353) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.4.1.jar:2.4.1]
	... 6 more
Caused by: java.lang.RuntimeException: Demo certificates found [d14aefe70a592d7a29e14f3ff89c3d0070c99e87d21776aa07d333ee877e758f, 54a70016e0837a2b0c5658d1032d7ca32e432c62c55f01a2bf5adcb69a0a7ba9, bdc141ab2272c779d0f242b79063152c49e1b06a2af05e0fd90d505f2b44d5f5, 3e839e2b059036a99ee4f742814995f2fb0ced7e9d68a47851f43a3c630b5324, 9b13661c073d864c28ad7b13eda67dcb6cbc2f04d116adc7c817c20b4c7ed361]
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:378) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:426) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.node.Node.<init>(Node.java:353) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.4.1.jar:2.4.1]
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.4.1.jar:2.4.1]
	... 6 more
uncaught exception in thread [main]
java.lang.IllegalStateException: failed to load plugin class [org.opensearch.security.OpenSearchSecurityPlugin]
Likely root cause: java.lang.RuntimeException: Demo certificates found [d14aefe70a592d7a29e14f3ff89c3d0070c99e87d21776aa07d333ee877e758f, 54a70016e0837a2b0c5658d1032d7ca32e432c62c55f01a2bf5adcb69a0a7ba9, bdc141ab2272c779d0f242b79063152c49e1b06a2af05e0fd90d505f2b44d5f5, 3e839e2b059036a99ee4f742814995f2fb0ced7e9d68a47851f43a3c630b5324, 9b13661c073d864c28ad7b13eda67dcb6cbc2f04d116adc7c817c20b4c7ed361]
	at org.opensearch.security.OpenSearchSecurityPlugin.<init>(OpenSearchSecurityPlugin.java:378)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:781)
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:730)
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:532)
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:195)
	at org.opensearch.node.Node.<init>(Node.java:426)
	at org.opensearch.node.Node.<init>(Node.java:353)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
For complete error details, refer to the log at /usr/share/opensearch/logs/search-cinc.log
```

**Comment by jdblack** [comment]
This was my own mistake.  The proper format for extraEnvs is 
```
  opensearch_values = [ yamlencode({
    extraEnvs = [
      {
        name = "DISABLE_INSTALL_DEMO_CONFIG"
        value = "true"
      }
    ]
...
```
